MusicsApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show]
  resource :sessions, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index]
end

MusicsApp/app/models/album.rb
class Album < ApplicationRecord
validates :band_id, presence: true

  belongs_to :band

end

MusicsApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MusicsApp/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums, dependent: :destroy

end

MusicsApp/app/models/user.rb
class User < ApplicationRecord

  validates :email, :session_token, :password_digest, presence: true
  validates :email, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  attr_reader :password

  def User.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def User.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user && user.is_password?(password)
      return user
    end
    nil
  end



end

MusicsApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to band_url(params[:album][:band_id])
    else
      flash.now[:error] = @album.errors.full_messages
      render band_url(params[:album][:band_id])
    end
  end

  def edit
    @album = Album.find(id: params[:id])
    render :edit
  end

  def show

  end

  def update
  end

  def destroy
    @album.find_by(id: params[:id])
  end

  private

  def album_params
    params.require(:album).permit(:band_id, :title, :year, :studio)
  end
end

MusicsApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    return nil if !session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    if current_user
      return true
    else
      false
    end
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end



end

MusicsApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band.id)
    else
      flash.now[:error] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    @band.update(band_params)
    redirect_to band_url(@band.id)
  end

  def destroy
    @band = Band.find_by(name: band_params)
    @band.delete
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end

end

MusicsApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
  render :new
end

def create
  @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
  if @user
    log_in_user!(@user)
    redirect_to user_url(@user.id)
  else
    flash.now[:error] = ["Incorrect Email or Password"]
    render :new
  end
end

def destroy
  user = current_user
  user.reset_session_token!
  session[:session_token] = nil
  redirect_to new_sessions_url
end

end

MusicsApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user.id)
    else
      flash.now[:error] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = current_user
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end

end

MusicsApp/app/helpers/albums_helper.rb
module AlbumsHelper
end

MusicsApp/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input type='hidden'
           name='authenticity_token'
           value='#{ form_authenticity_token }'>".html_safe
  end

end

MusicsApp/app/helpers/bands_helper.rb
module BandsHelper
end

MusicsApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

MusicsApp/app/helpers/users_helper.rb
module UsersHelper
end

MusicsApp/app/views/bands/_form.html.erb
<% if action == :new %>
  <% action_url = bands_url %>
<% else %>
  <% action_url = band_url(band.id) %>
<% end %>

<form action="<%= action_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <%= auth_token %>


  <label for="band_name">Name</label>
  <input type="text" name="band[name]" value="<%= band.name %>">

  <input type="submit" value=" <%= (action == :edit) ? 'Update Band' : 'Create Band' %> ">
</form>

MusicsApp/app/views/bands/edit.html.erb
<%= render 'form', band: @band, action: :edit %>

MusicsApp/app/views/bands/index.html.erb
<h1>Our Bands!</h1><br>

<ul>
  <% @bands.each do |band| %>
  <li> <%= band.name %>  </li>
  <% end %>
</ul>

MusicsApp/app/views/bands/new.html.erb
<%= render 'form', band: @band, action: :new %>

MusicsApp/app/views/bands/show.html.erb
This is the page of <%= @band.name %>!
<br>
<%= button_to "Update Band Name", edit_band_url(@band), method: :get %><br>


<% @band.albums.each do |album| %>
  <%= album.title %><br>
  <%= album.year %><br>
  <%= album.studio ? "Studio Album" : "Live Album" %><br>
<% end %>

<form action=" <%= albums_url %> " method="post">
  <input type="hidden" name="album[band_id]" value=" <%= @band.id %> ">
  <%= auth_token %>

  <label for="title">Album Title</label>
  <input type="text" name="album[title]"><br>

  <label for="year">Release Year</label>
  <input type="text" name="album[year]" value=""><br>

  <label for="studio">Studio Album?</label>
  <input type="radio" name="album[studio]" value="true">True
  <input type="radio" name="album[studio]" value="false">False<br>


  <input type="submit" value="Add Album">

</form>

MusicsApp/app/views/layouts/_header.html.erb
<div class="header">
  <div class="image_header">
  </div>
  <h1 class="main_title">music app</h1>
  <div class="header-content">
    <% if current_user %>
      <%= button_to "Log Out", sessions_url, method: :delete %>
    <% else %>
      <%= button_to "Sign Up", new_user_url, method: :get %><br>
      <%= button_to "Log In", new_sessions_url, method: :get %><br>
    <% end %>
  </div>
</div>

MusicsApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="header">
      <%= render "/layouts/header" %>
    </div>
    <div class="main-content">
      <%= yield %>
    </div>
  </body>
</html>

MusicsApp/app/views/shared/_errors.html.erb
<% if flash[:error] %>
  <ul>
    <% flash[:error].each do |error| %>
      <li><%= error %></li>
  </ul>
  <% end %>
<% end %>

MusicsApp/app/views/users/new.html.erb
<form action=" <%= users_url %> " method="post">

  <%= auth_token %>

  <label for="email">Email</label>
  <input type="text" name="user[email]"> <br>

  <label for="password">Password</label>
  <input type="password" name="user[password]"><br>

  <input type="submit" value="Create User">
</form>

MusicsApp/app/views/users/show.html.erb
<h1 class="show-page">Hello User! </h1>